services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'
            $requestStack: '@request_stack'
            $db: '@database_connection'
            $slug: '@contao.slug'
            $insertTagParser: '@contao.insert_tag.parser'
            $csrfTokenManager: '@contao.csrf.token_manager'
            $csrfTokenName: '%contao.csrf_token_name%'
            $calendarExport: '@Cgoit\ContaoCalendarIcalBundle\Backend\CalendarExportController'
            $icsExport: '@Cgoit\ContaoCalendarIcalBundle\Export\IcsExport'
            $timezoneUtil: '@Cgoit\ContaoCalendarIcalBundle\Util\TimezoneUtil'

    _instanceof:
        Cgoit\ContaoCalendarIcalBundle\Util\TimezoneUtilAwareInterface:
            calls:
                - [ 'setTimezoneUtil', [ '@Cgoit\ContaoCalendarIcalBundle\Util\TimezoneUtil' ] ]


    Cgoit\ContaoCalendarIcalBundle\:
        resource: ../src/*

    Cgoit\ContaoCalendarIcalBundle\Backend\CalendarImportFileController:
        public: true
